name:                brackets-hs
version:             0.1.0.0
github:              "dima-starosud/brackets-hs"
license:             BSD3
author:              "Dmytro Starosud"
maintainer:          "d.starosud@gmail.com"
copyright:           "2019 Dmytro Starosud"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dima-starosud/brackets-hs#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  brackets-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - brackets-hs

tests:
  brackets-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - brackets-hs
